FROM python:3
WORKDIR /usr/src/app
# COPY ./fcore/requirements.txt ./
COPY ./fcore ./fcore
WORKDIR /usr/src/app/fcore
RUN pip install --no-cache-dir -r ./requirements.txt
ENTRYPOINT ["python", "fcore.py", "start"]

